{{- if .Capabilities.APIVersions.Has "jenkins.io/v1/Release" }}
apiVersion: jenkins.io/v1
kind: Release
metadata:
  creationTimestamp: "2021-03-10T16:15:34Z"
  deletionTimestamp: null
  name: '{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}'
spec:
  commits:
  - author:
      email: jenkins-x@googlegroups.com
      name: jenkins-x-bot
    branch: master
    committer:
      email: jenkins-x@googlegroups.com
      name: jenkins-x-bot
    message: |
      chore: release 0.0.22
    sha: cd961284ec71a428148fbf1cb1a98f68bd1ac950
  - author:
      email: jenkins-x@googlegroups.com
      name: jenkins-x-bot
    branch: master
    committer:
      email: jenkins-x@googlegroups.com
      name: jenkins-x-bot
    message: |
      chore: add variables
    sha: 25b370f1c2c1a8b453cc8dbb8cfeb0cce9665a24
  - author:
      email: salaboy@gmail.com
      name: salaboy
    branch: master
    committer:
      email: salaboy@gmail.com
      name: salaboy
    message: |
      updating deployment for servicemonitor and updating tracing config
    sha: efb7d665d3d19ad50511190f5c51f355f86c1d5c
  gitHttpUrl: https://github.com/salaboy/fmtok8s-agenda-rest
  gitOwner: salaboy
  gitRepository: fmtok8s-agenda-rest
  name: '{{ .Chart.Name }}'
  releaseNotesURL: https://github.com/salaboy/fmtok8s-agenda-rest/releases/tag/v0.0.23
  version: v0.0.23
status: {}
 
{{- end }}
