{{- if .Capabilities.APIVersions.Has "jenkins.io/v1/Release" }}
apiVersion: jenkins.io/v1
kind: Release
metadata:
  creationTimestamp: "2021-02-26T01:41:28Z"
  deletionTimestamp: null
  name: '{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}'
spec:
  commits:
  - author:
      email: jenkins-x@googlegroups.com
      name: jenkins-x-bot
    branch: master
    committer:
      email: jenkins-x@googlegroups.com
      name: jenkins-x-bot
    message: |
      chore: release 0.0.15
    sha: 1afce02feffa950854cf5318d0935653f999b75c
  - author:
      email: jenkins-x@googlegroups.com
      name: jenkins-x-bot
    branch: master
    committer:
      email: jenkins-x@googlegroups.com
      name: jenkins-x-bot
    message: |
      chore: add variables
    sha: 346d9a84bcf4337c5deec9a1d11ceabaaeb54bba
  - author:
      email: Salaboy@gmail.com
      name: salaboy
    branch: master
    committer:
      email: noreply@github.com
      name: GitHub
    message: Update README.md
    sha: 4254dd06a319dce620c618da9a80637334cd95e9
  - author:
      email: Salaboy@gmail.com
      name: salaboy
    branch: master
    committer:
      email: noreply@github.com
      name: GitHub
    message: Update README.md
    sha: be8594400677410d550b187b95121dfdb06fe680
  - author:
      email: salaboy@gmail.com
      name: salaboy
    branch: master
    committer:
      email: salaboy@gmail.com
      name: salaboy
    message: |
      adding tracing config
    sha: a56d2e1cc3734154c5dc6e278dfb9ed34a418823
  gitHttpUrl: https://github.com/salaboy/fmtok8s-agenda-rest
  gitOwner: salaboy
  gitRepository: fmtok8s-agenda-rest
  name: '{{ .Chart.Name }}'
  releaseNotesURL: https://github.com/salaboy/fmtok8s-agenda-rest/releases/tag/v0.0.16
  version: v0.0.16
status: {}
 
{{- end }}
