name: From Monolith to K8s (Github Actions)
on: [push]

env:
  OWNER: salaboy
  GH_PAGES_BRANCH_NAME: gh-pages

permissions:
  packages: write

jobs:
  Publish-Github-Registry:
    runs-on: ubuntu-20.04
    steps:
      # Info [LOGGER]
      # It shows what branch or tag name that triggered the workflow run. 
      - name: Info
        run: echo "Building ${{ github.repository }} application, branch/tag ${{ github.ref_name}}"

      # Set up QEMU [SETUP] https://github.com/docker/setup-qemu-action
      # GitHub Action to install QEMU static binaries 
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      # Set up Docker Buildx [SETUP] https://github.com/docker/setup-buildx-action
      # GitHub Action to set up Docker Buildx.
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      # Set up Docker Meta [UTIL] https://github.com/docker/metadata-action
      # GitHub Action to extract metadata from Git reference and GitHub events.
      # This action is used with Docker Build Push action to tag and label Docker images.
      - name: Set up Docker Meta
        id: docker_meta
        uses: docker/metadata-action@v3
        with:
          images: |
            ghcr.io/${{ github.repository }}
          #  About tag inputs: https://github.com/docker/metadata-action#tags-input
          #  This action uses 'type=semver' and 'type=ref' to create tag name with the branch or tag name.
          tags: |
            type=ref,event=branch
            type=ref,event=pr,
            type=semver,pattern={{raw}}

      # Checkout and Set up JDK 11 [CHECKOUT, SETUP] https://github.com/actions/setup-java
      # Github Action to set up JDK 11
      - uses: actions/checkout@v3
      - name: Checkout and Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: adopt

      # Build application [BUILD]
      - name: Build application
        run: mvn package

      # Login to Github Container Registry [AUTH] https://github.com/docker/login-action
      # GitHub Action to login against a Docker registry.
      - name: Login to Gitub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ env.OWNER }}
          # It needs to be added on Github repository 
          # https://github.com/salaboy/fmtok8s-agenda-rest/settings/secrets/actions
          password: ${{ secrets.PACKAGE_TOKEN }}
      
      # Build and Push Docker Image [BUILD, PUBLISH] https://github.com/docker/build-push-action
      # GitHub Action to build and push Docker images with Buildx.
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
      
      # Change Chart.yml [UTIL] https://github.com/fjogeleit/yaml-update-action
      # Github Action to change a local YAML file without commiting the change.
      - name: Change Chart.yml
        uses: fjogeleit/yaml-update-action@main
        # This is necessary because the property 'version' on Chart.yml must be a valid Semver 2 version.
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          valueFile: 'helm/fmtok8s-api-gateway/Chart.yaml'
          propertyPath: 'version'
          value: '${{ github.ref_name }}'
          commitChange: false
          updateFile: true

      # Release Helm Chart [BUILD, PUBLISH] https://github.com/stefanprodan/helm-gh-pages
      # A GitHub Action for publishing Helm charts with Github Pages.
      - name: Release Helm Chart
        uses: stefanprodan/helm-gh-pages@master
        with:
          charts_dir: helm
          # It needs to be added on Github repository 
          # https://github.com/salaboy/fmtok8s-agenda-rest/settings/secrets/actions
          token: ${{ secrets.PACKAGE_TOKEN }}
          repository: helm
          branch: ${{ env.GH_PAGES_BRANCH_NAME }}
          owner: ${{ env.OWNER }}


          



    